config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :products do
    resources :reviews, only: [:show, :create, :destroy]
  end

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :reviews
  has_many :users, through: :reviews

  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  validates :comment, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def ensure_logged_in
    unless current_user
      flash[:alet] = 'Please log in'
      redirect_to new_session_path
    end
  end
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = if params[:search]
      Product.where("LOWER(name) LIKE LOWER (?)", "%#{params[:search]}%")
    else
      Product.all
    end

    @products = @products.order('products.created_at DESC').page(params[:page])
    @products_all = Product.all
    # if request.xhr?
    #   render @products

    respond_to do |format|
      format.html
      format.js
    end
  end



  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_product
  before_action :ensure_logged_in, only: [:create, :destroy]

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to product_path(@product.id), notice: 'Review added.'}
        format.js {}
      else
        format.html { render 'products/show', alert: 'There was an error.'}
        format.js{}
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private

  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, notice: 'Logged in!'
    else
      flash.now[:alert] = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_url, notice: 'Signed up!'
    else
      render 'new'
  end
end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <title>Rainforest</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if flash[:notice] %>
    <p id='notice'><%= flash[:notice] %></p>
    <% end %>

    <% if flash[:alert] %>
    <p id='alert'><%= flash[:alert] %></p>
  <% end %>

    <%= yield %>

    <p class='userinfo'>
      <% if current_user %>
        Signed in as <%= current_user.name %>. <%= link_to 'Log out',
          session_path('current'), :method => :delete %>
      <% else %>
        <% link_to 'Log in', new_session_path %> or <%= link_to 'Sign up',
            new_user_path %>
      <% end %>
    </p>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %>
        prohibited this product from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %> <br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :price_in_cents %> <br>
    <%= f.text_field :price_in_cents %>
  </div>

  <div class="actions">
    <%= f.submit 'Save' %>
  </div>

  <% end %>

app/views/products/_product.html.erb
  <p>
    <%= link_to product.name, "products/#{product.id}" %>
    <%= product.name %>
    <%= product.description %>
    <%= product.formatted_price %>
  </p>

app/views/products/_review_form_errors.html.erb
<div id='review-form-errors'>
  <% if @review.errors.any? %>
      <div id='error_explanation'>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
</div>

app/views/products/_reviews.html.erb
<p> Reviews for <%= @product.name %> </p>
<% @product.reviews.each do |review| %>
<p class ="comment">
  <%= review.comment %>
  <br/>
  <% if review.user != nil %>
    <em> by <%= review.user.name %></em>
    Added on: <%= review.created_at %>
  <% end %>
</p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Picture</h1>

  <%= form_for @product do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %> <br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :price_in_cents %> <br>
    <%= f.text_field :price_in_cents %>
  </p>

  <p>
    <%= f.submit %>
  </p>

  <% end %>

app/views/products/index.html.erb
<h1>Products (<%= @products_all.length %>)</h1>
<%= link_to 'New Product', new_product_path %>

<!-- <h1><small><%= page_entries_info @products %></small></h1> -->

<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag 'search' %>
<% end %>

<div id= 'products'>
  <%= render @products %>
</div>

<%= paginate @products %>

<!-- <script type="text/javascript">
  function display_search_results() {
    if (this.readyState === 4) {
      console.log(this);
      document.getElementById('products').innerHTML = this.responseText;
    }
  }

  var form = document.getElementById('search-form');
  form.addEventListener('submit', function(e) {
    e.preventDefault();
    var searchValue = document.getElementById('search').value;
    var xhr = new XMLHttpRequest();
    xhr.onload = display_search_results;
    xhr.open('GET', '/products?search=' + searchValue, true);
    xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
    xhr.send();
  });
</script> -->

app/views/products/index.js.erb
// $('#products').html("<%=j (render @products) %>");
<%if params[:search] && params[:page].nil? %>
  $('#products').html('<%= j(render @products) %>');
<% else %>
  $('#products').append('<%= j (render @products) %>');
<% end %>

$('.pagination').replaceWith('<%= j (paginate @products) %>');

app/views/products/new.html.erb
<h1>Add a new Product</h1>
<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h3>Reviews</h3>

<p>
  <%= @product.name %>, <%= @product.description %>, <%= @product.formatted_price %>
</p>

<div id="review-list">
  <%= render :partial => 'reviews' %>
</div>


<% if current_user %>
  <h4>New Review</h4>

<%= form_for [@product, @review], :remote => true do |f| %>

<div id="review-form-errors">
  <%= render :partial => "/products/review_form_errors" %>
</div>

  <div class='field'>
    <%= f.label :comment %> <br/>
    <%= f.text_area :comment %>
  </div>
  <div class='actions'>
    <%= f.submit %>
  </div>
  <% end %>

  <% else %>
  <p>Please <%= link_to 'log in', new_session_path %> to add a review </p>
  <% end %>

<%= link_to 'Back to Products', products_url %>
<%= link_to 'Edit', edit_product_path(@product) %>
<%= link_to 'Delete', @product, method: :delete,
  data: {confirm: 'Are you sure you want to delete this product?'} %>

<script type="text/javascript">
  $(function() {
    $("#new_review")
      .on('ajax:beforeSend', function() {
        $("input[type= 'submit']")
          .val('saving...')
          .attr('disabled', 'disabled');
      })
      .on('ajax:complete', function() {
        $("input[type='submit']")
          .val('create Review')
          .removeAttr('disabled')
      });
  });
</script>
  <!-- <script type="text/javascript">
    $(document).ready(function() {
      $("#new_review")
        .on('ajax:beforeSend', function() {alert("loading!");})
        .on('ajax:success', function(data, status, xhr) {alert("success!");})
        .on('ajax.error', function(xhr, status, error) {alert("error!");})
        .on('ajax.complete', function() {alert("complete!");});
    });
  </script> -->

app/views/products/show.js.erb
$('body').append("<%= escape_javascript(render @product) %>");

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/create.js.erb
// alert("I'm responding to your request!");
$("#review-list").html("<%= j(render(:partial => 'products/reviews')) %>");
<% if @review.errors.present? %>
  $("#review-form-errors")
    .html("<%= escape_javascript(render(:partial => '/products/review_form_errors')) %>");
<% else %>
  $("#review-form-errors").html(" ");
  $("#review-list").html("<%= j(render(:partial => '/products/reviews')) %>");
  $("#new_review")[0].rest();
<% end %>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %> </div>
<% end %>